version: '3.6'

services:
    mongo:
        image: mongo:7.0
        container_name: mongo
        ports:
            - 27017:27017
        command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
            interval: 5s
            timeout: 30s
            retries: 30
        volumes:
            - "mongo_data:/data/db"
            - "mongo_config:/data/configdb"
        networks:
            - docker-network

volumes:
    mongo_data:
    mongo_config:

networks:
    docker-network:
        driver: bridge